### ISSUE TITLE
Pre-applied filters are not shown on Jobs page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#109]
When I click "List jobs" for a given workflow, I get to a Jobs page with a pre-applied workflow filter. But the workflow filter box does not show which filter had been applied, instead it is blank.

See: https://drive.google.com/file/d/1fDJExSifGJQ4wHYQFW7v2DCKZlhPY-fr/view?usp=sharing

**Comment by tcompa** [comment]
Possibly related to #105?

**Comment by jluethi** [comment]
Hmm, possible. But I don't see any relevant errors in the browser console, see:
<img width="1710" alt="Screenshot 2023-04-18 at 10 07 49" src="https://user-images.githubusercontent.com/18033446/232713601-77a3d1f9-6c5a-4c05-be45-4d93275ff3d3.png">

(the error there was from some tests before, loading the job page doesn't trigger new errors)

**Comment by tcompa** [comment]
I fixed my comment

**Comment by tcompa** [comment]
More context:
When we access a table with some parameters in the URL, we want a strict selection of rows.
When we are interactively browsing it, the "contains" match seems more natural.

If this is too confusing, we can enforce the strict "is-equal-to" comparison also in the interactive filtering.

**Comment by jluethi** [comment]
Hmm, let's maybe discuss at tomorrow's call. I'm not sure I understand the difference e.g. in workflow filtering, because the interactive filtering also just allows me to select an existing workflow from a drop-down => applies the same filter as the one set via URL. It's not looking for workflows that contain that name, but just the exact match even in the interactive filtering (which makes sense to me when using dropdowns).

I anyway don't see a interactive filter anymore for the IDs and all other filters seem to be dropdowns.

**Comment by tcompa** [comment]
That's right, I was referring to some slightly out-of-date discussion - which is only relevant for ID columns with free-text filter (rather than dropdown options).

But, as you noted,
> I anyway don't see a interactive filter anymore for the IDs

I suggested to  remove this, as I don't expect users to look for a specific job ID in the table.

---

That said, it's probably doable to pre-fill the dropdown filter from the URL.

What remains unclear to me is the possible overlap between URL/interactive filters, e.g. as in
* I click on "list jobs" in the workflow list
* I am redirected to a page with a certain `workflow_id` specified in the URL
* The dropdown menu already selects the relevant workflow (the one with `workflow_id`)
* I select a different workflow from the dropdown menu, and the displayed table is updated (but not the URL)
* I click "clean filters".. what happens? I go back to the state defined in the URL, or to a full table with no filters?

(nothing so relevant, but to be clarified)

**Comment by jluethi** [comment]
Intuitively, I'd expect "clean filters" to remove all the filters that are applied. In our current setup, that would probably work well (and I think that's what it's always doing now).

And reloading the page could either get to a page without filters applied (most user likely won't think of the URL and the filters pre-specified there) or to one with the original filters applied from the redirect (that's what it currently does).

----

We may get to job pages that are not project specific anymore, i.e. offer a general jobs page to the user. In the project, they are always just shown for that project and I think I'd still expect that to stay that way even if a user clears filters, but not really sure there yet.

**Comment by rkpasia** [comment]
- [ ] select an existing workflow from a drop-down => applies the same filter as the one set via URL

**Comment by jluethi** [comment]
Interface should match query parameters

**Comment by tcompa** [comment]
Expected behavior

Page `.../jobs?workflow=25` correctly shows only the jobs related to workflow with ID=25, but the interface shows "All" in the workflow filter.

It should show the name of workflow 25.
