### ISSUE TITLE
Successful jobs should show the workflow.log in their log entry

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#122]
Currently (current fractal-web, server 1.2.0a5), clicking on log for a job that ran successfully, it just shows an empty log. Instead, we'd want to show the workflow log there.

<img width="1363" alt="Screenshot 2023-04-19 at 18 58 31" src="https://user-images.githubusercontent.com/18033446/233147878-865766a6-35b2-4c4c-8c37-0774bc6eb1ed.png">

@tcompa I thought there was an issue on this somewhere (maybe server-side?), but I couldn't find anything anymore, so I opened this one so we can track progress towards adding this on Fractal web.

**Comment by tcompa** [comment]
> @tcompa I thought there was an issue on this somewhere (maybe server-side?), but I couldn't find anything anymore, so I opened this one so we can track progress towards adding this on Fractal web.

Ref:
* https://github.com/fractal-analytics-platform/fractal-server/issues/618

**Comment by tcompa** [comment]
Fixed with https://github.com/fractal-analytics-platform/fractal-server/pull/635, part of the upcoming fractal-server=1.2.0 release.

No action is needed on fractal-web, see screenshot
![Screenshot from 2023-04-20 08-51-20](https://user-images.githubusercontent.com/3862206/233284292-71a63a4e-c157-40fe-a3df-f6dcd1fc87d7.png)

**Comment by tcompa** [comment]
fractal-server=1.2.0 is now released
