### ISSUE TITLE
Adding Fractal-reserved args to meta args fails

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#157]
This is for the old way of adding parameters to tasks and this behavior only shows up for what I think are Fractal-reserved meta arguments (e.g. `parallelization_level`, `mem` etc).

When adding a new meta argument to a task, the newly added argument just disappears.
In the console, I see a "Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)"

If I try to add the same argument again, I get a "Property name "parallelization_level" is already used" displayed in the interface.

If I reload the page, I can add it again (though again hit a 422 in the console).

When downloading the workflow, the newly added argument is not there.

----

I can add new args like test. But those aren't meaningful. It's important that a user can add args like mem to overwrite the preset mem setting. This is how a user would overwrite a meta arg.

While input_paths, output_paths etc. are types of arguments the user shouldn't be able to set themselves, the meta args are something the user needs to be able to edit. 

If we move towards the task schemas here, then those meta args should probably already be shown and the user could just edit them. Then, this only affects the old setup, but because we want to keep using that as a fallback, we should still fix this bug

**Comment by tcompa** [comment]
This issue is a mix of fractal-server and fractal-web. Here are some clarifications:

> This is for the old way of adding parameters to tasks and this behavior only shows up for what I think are Fractal-reserved meta arguments (e.g. parallelization_level, mem etc).

1. In the current state, `parallelization_level` is a protected key of `meta`, see https://github.com/fractal-analytics-platform/fractal-common/blob/main/schemas/workflow.py#L56. This was put in place long time ago, because we expect each task to have a single parallelization level which does not change over time. We can of course relax this constraint, if it's preferred.
2. `mem` or other attributes have not special meaning: they are not reserved keywords, and they can be modified.

> If I try to add the same argument again, I get a "Property name "parallelization_level" is already used" displayed in the interface.

This is, I guess, a fractal-web issue. @rkpasia what happens if the server responds with an error (e.g. 422)? Maybe there is a local copy of the `meta` objects that should be reverted to its previous state?

> I can add new args like test. But those aren't meaningful. It's important that a user can add args like mem to overwrite the preset mem setting. This is how a user would overwrite a meta arg.

I'd expect that this is already working. If not, let's debug it further.

> If we move towards the task schemas here, then those meta args should probably already be shown and the user could just edit them. Then, this only affects the old setup, but because we want to keep using that as a fallback, we should still fix this bug

I think we never mentioned JSON schemas for the `meta` arguments, yet. Of course  they would be useful, and it should be doable (it's essentially the same as for the standard `args`), but we should first make an effort to define what's the allowed structure - and how it varies depending on the FRACTAL_BACKEND (e.g. is it a single schema that is general for all backends? or do we have a schema for each backend?). We should also understand where are these schemas defined (e.g. the SLURM configuration is fully handled in fractal-server, so that's the most likely place where we would need to create the schemas and keep them up-to-date. But then should we somehow validate the defaults of a FRACTAL_MANIFEST in the task repo?). I think this issue is still to be explored further, before any implementation.

**Comment by jluethi** [comment]
Ah, good to know. If the only thing we can't edit is `parallelization_level`, I'm fine with making sure this is already set during task registration (or via task edit). Then the thing we should fix now would just be this part:

>>  If I try to add the same argument again, I get a "Property name "parallelization_level" is already used" displayed in the interface.

> This is, I guess, a fractal-web issue. @rkpasia what happens if the server responds with an error (e.g. 422)? Maybe there is a local copy of the meta objects that should be reverted to its previous state?

And agreed, let's discuss meta schemas on the server side first, before any implementation
