### ISSUE TITLE
Interpret empty arrays/objects as null, for first-level arguments 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#205]

**Comment by tcompa** [comment]
If the user interaction leads to argument `x` equal to an empty array `[]` and argument `y` equal to an empty object `{}`, these arguments should not be part as the PATCH args payload.

**Comment by tcompa** [comment]
> We shall expect the stripping behaviour of the client to remove both empty objects and empty arrays.

Agreed.

> The described behaviour shall also work for nested objects and lists.
> A NOT TRIVIAL EXAMPLE
> ...

This second case is postponed to a future implementation, because it's not yet clear whether it is the expected behavior.

**Comment by rkpasia** [comment]
This feature leads to a problem!

Given the following schema, with highlight to the specific property:

```json
"allowed_channels": {
      "title": "Allowed Channels",
      "type": "array",
      "items": {
        "$ref": "#/definitions/OmeroChannel"
      },
      "description": "A list of ``OmeroChannel`` s, where each channel must include the ``wavelength_id`` attribute and where the ``wavelength_id`` values must be unique across the list."
    }
...
"required": [
    "input_paths",
    "output_path",
    "metadata",
    **"allowed_channels"**
  ],
```

The client, during the stripping procedure, transforms the following object

```javascript
{
    "image_extension": "tiffany",
    "num_levels": 5,
    "coarsening_xy": 2,
    "image_glob_patterns": [],
    "allowed_channels": [],
    "metadata_table_file": null
}
```

into, after the stripping procedure

```javascript
{
    "image_extension": "tiffany",
    "num_levels": 5,
    "coarsening_xy": 2
}
```

Which prevents the client to save the changes because the AJV validation states the following error:

```javascript
[
  {
    "instancePath": "",
    "schemaPath": "#/required",
    "keyword": "required",
    "params": {
      "missingProperty": "allowed_channels"
    },
    "message": "must have required property 'allowed_channels'"
  }
]
```

In essence, removing the default `"allowed_channels: []"` would prevent the capability to ever save the changes of args in this situation.
