### ISSUE TITLE
Support OAuth2 login

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#246]
See https://fractal-analytics-platform.github.io/fractal-server/internals/users (and especially the OAuth2 section).

When working on this, let's also move away from `formData` (ref #265).

**Comment by tcompa** [comment]
This was mostly closed with #333.

> When working on this, let's also move away from formData (ref https://github.com/fractal-analytics-platform/fractal-web/issues/265).

Question for @zonia3000: did #333 also fix this formData part of the current issue? If so, let's close it.

**Comment by zonia3000** [comment]
In #333 I didn't remove `formData` because I realized that the login needs a custom Svelte backend logic to extract the token from the response and set the cookie. This can't be done by the frontend code because for security reason it is not possible to manipulate the cookie from the frontend (it's an HttpOnly cookie).
I could remove the `formData` but I would still have to implement a duplicated logic on the backend, so I don't see any benefit in doing that. I would treat it as a special case.

**Comment by tcompa** [comment]
Thanks for the explanation!

Then this issue can be closed.
