### ISSUE TITLE
Run workflow from beginning to task X without selecting the first task

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#256]
> > From a user perspective, many users may want to run from beginning to task X, so just setting the second entry would be logical.
> 
> This is currently available by selecting the first task (first) and then selecting the last task to be task X.
> But we are not updating it so that selecting the first task is not required.
> 
> _Originally posted by @tcompa in https://github.com/fractal-analytics-platform/fractal-web/issues/89#issuecomment-1689624121_

Will be nice to eventually add support so that a first selection is not necessary. If nothing is selected for the first task, it runs the workflow from the beginning but it's still possible to add an end task. 
Nothing urgent though, issue just to keep track of this feature wish.

**Comment by tcompa** [comment]
My bad, "But we are not updating it so that selecting the first task is not required." was meant to read "But we are **now** updating it so that selecting the first task is not required.".

This is already fixed with [9a9d500](https://github.com/fractal-analytics-platform/fractal-web/commit/9a9d5008ed6f12d8278589d4df97b8fa409b4dbe). Any additional feedback from real-life testing is welcome.

**Comment by jluethi** [comment]
😂 ah, thanks! Great to see this! Will start testing it when I get a chance and provide feedback then
