### ISSUE TITLE
Have a job page for all jobs of a user across projects

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#284]
Feedback from Silvia:

> It would be nice if we could have one view of all Jobs running per user. At the moment I can see the status of my jobs, but only per project, so if I have two projects I need to switch to get an overview of what is done and what is still running

We should brainstorm good ways to make this accessible, would indeed be a nice overview to have.

**Comment by jluethi** [comment]
cc @silvbarb

**Comment by tcompa** [comment]
Thanks for this feedback!

Here is a naive proposed implementation:
1. We currently have some "List Jobs" button, at the workflow or project level. In case it's useful, we can turn them into "List project jobs" and "List workflow jobs".
2. We can add a new "Jobs" page to the main menu, which would then become: Home, Projects, Tasks, Jobs. That page would call the `GET /api/v1/project/` endpoint of fractal-server to fetch all jobs related to the current user's projects, and then we can display them almost in the same way as in the current `/projects/{projectId}/jobs` page (that is, with a _datatables_ table with a bunch of columns which offer sorting and filtering).

Would this simple update work? Is there any other aspect we may want to consider?

**Comment by jluethi** [comment]
Yes, I think that proposal is how I'd imagine an implementation of this. Would certainly make a good first implementation :) 

> We currently have some "List Jobs" button, at the workflow or project level. In case it's useful, we can turn them into "List project jobs" and "List workflow jobs".

I think we can keep their names the same for the moment.

If that project page has the same logic as our current project pages (just showing all projects), users can then filter by all the necessary parts.

We'll need to see how well that scales to users with e.g. 50 projects, each project having 10 datasets and 4 workflows.

-----

A second thought: Are those actually different pages or just ways to have different pre-set filters? At the moment, the "List project jobs" and "List workflow jobs" pages are the same, just that "List workflow jobs" has the filter preset for the workflow. If there is an additional filter level "project", then both existing project pages have that filter preset, while the new overall job page would have no filter set. But a user could go to any job page and by changing the filters see all the subset they want.

**Comment by tcompa** [comment]
> A second thought: Are those actually different pages or just ways to have different pre-set filters?

They would need to be different only if we decide to display different data depending on whether it's at a user level or project level (e.g. at the project level we may want to avoid the "project" column, since it would be the same value for all rows).

If we ignore this detail (or at least we find a reasonable workaround for making the table content a bit less verbose, for which I think we can come up with multiple solutions..), then we could use a single page. Different links would set different filters: the "List job" button in a Project page would set `project_id=XXX`, the "Jobs" link in the top menu would not set any filter, and so on..

Another difference concerns the fractal-server API calls. If the page is a single one, then it will always fetch the whole list of a user's projects and add the corresponding jobs to the table (independently on what will be displayed, which depends on filters). If the per-project page is a specific one, then we can make a "lighter" API call which only fetches a specific project and adds the corresponding jobs to the table.
If a user has 50 projects, there is obviously a (possible) 50x increase in response size. I cannot say right now how much it will affect performances - but we can prepare some stress-test (with many projects, datasets, workflows, ...) and verify.

**Comment by jluethi** [comment]
Sounds good. Not urgent to tackle, but let's look into this when we're improving web UX and evaluate which direction makes most sense :)

**Comment by tcompa** [comment]
Superseded by #318
