### ISSUE TITLE
Always sort by jobs starting from latest start-time

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#294]
Does the job page have a default sorting? If so, I can't figure out what it is.

It would make sense to sort by default by ID/Start Time (the sorting for both should be equivalent). Newest job should be on top.

**Comment by tcompa** [comment]
> It would make sense to sort by default by ID/Start Time (the sorting for both should be equivalent).

Agreed, we should always have a well-defined default sorting.

I think we are currently not setting any default sorting, since in https://github.com/fractal-analytics-platform/fractal-web/blob/main/src/routes/projects/%5BprojectId%5D/jobs/%2Bpage.svelte we just use
```js
tableHandler = new DataHandler(jobs);
```

I think we would just need to add
```js
tableHandler.sortDesc("id")
```
but that's to be checked.
