### ISSUE TITLE
Review `src/lib/types.d.ts`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#307]
I don't fully grasp the way this file is used, but it looks like it differs from the actual type of a task - see e.g. the `TaskRead` entry in https://fractal-analytics-platform.github.io/fractal-server/openapi.json.

**Comment by zonia3000** [comment]
I've introduced this file to remove several warnings about types not being correctly recognized. The TypeScript types specified in this file can be used with JSDocs comments to specify the expected type of a variable.

For example, using the `Task` type:

```
/** @type {import('$lib/types').Task|undefined} */
$: task = $taskStore;
```

In this way we can have type checking without porting everything to TypeScript.

I did this mostly to fix errors reported by the IDE, but many others can be fixed in this way (see `npm run check` output).

Regarding the difference you find I confirm that `args_schema` should be of type `object` and not `string` and also the property `meta` is missing. Thanks for pointing out the openapi.json file, the next time I'll update something on that file I'll check it.

**Comment by tcompa** [comment]
> I've introduced this file to remove several warnings about types not being correctly recognized. The TypeScript types specified in this file can be used with JSDocs comments to specify the expected type of a variable.
> 
> For example, using the `Task` type:
> 
> ```
> /** @type {import('$lib/types').Task|undefined} */
> $: task = $taskStore;
> ```
> 
> In this way we can have type checking without porting everything to TypeScript.
> 
> I did this mostly to fix errors reported by the IDE, but many others can be fixed in this way (see `npm run check` output).

That's great (and thanks for the explanation)

**Comment by tcompa** [comment]
Fixed with https://github.com/fractal-analytics-platform/fractal-web/pull/306/commits/fd71036b825af3eae2c282ec1f04babd969ff86a.
