### ISSUE TITLE
Use collapsible sections in Dataset.history

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#317]
As of v0.6.1, this looks like
![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/c2ab9220-f7d9-4032-9c16-e039185f3651)

Maybe we can turn each history item in a collapsed-by-default section? That way, the user would just expand relevant items to look at them in detail.

**Comment by jluethi** [comment]
I like the idea of making this page more accessible. Collapsible items is a good default. Another good change would be not just displaying the full content as a json string, but hat the first 2 levels displayed nicely, e.g. have each workflow-tasks be a collapsible, then in the workflow-task there are entries like meta, args, task (again), status, etc. Each of those top level items could also be displayed in a regular fashion.
The content of those can be just json strings as a start, otherwise the page gets unwieldy. But in that way, the history would look more approachable as an overview :)

**Comment by tcompa** [comment]
Regarding the "nice" display options:

Since this content is shown within `pre` tags, processing it is a bit more complex. The same complexity applied to work on the task logs (see https://github.com/fractal-analytics-platform/fractal-web/issues/373), but that had a stronger motivation since it is information that users see often. Dataset history is clearly more of a for-advanced-users information.

I propose we start with the simple solution (each history item is collapsible), which already makes it more readable (instead of a very long page) - and we can improve on this later.

**Comment by jluethi** [comment]
I like the "every item is collapsible" start. And if they are collapsed by default, the history gives a high-level view on what tasks ran and whether they succeeded or failed easily, plus more details on request for a given task

**Comment by zonia3000** [comment]
The collapsed dataset history, with 2 tasks:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/f0466e5e-2ed0-456d-9fed-6f193fb75064)

First task expanded:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/e57d6835-2118-464b-a0ac-83032130c9ec)
