### ISSUE TITLE
Running on localhost: Document that accessing Fractal web via http://127.0.0.1:5173 does not work

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#370]
Quick description of an issue @fstur ran into today:
On certain linux machines (can you say more on what the machine is @fstur ?), launching fractal web via the classical `npm run dev -- open` opens http://127.0.0.1:5173 instead of http://localhost:5173.
Fractal web is accessible there. But the login the fails silently, it just forwards the user to the login page with invalidate=True in the url. The reason is that Fractal web was configured somewhere to expect to talk to http://localhost:5173, but it was accessed via http://127.0.0.1:5173. Not sure if then the cookie is invalid or what happens.

It would be good to:

- [ ] Reproduce this behavior and figure out why no error is raised (neither in Fractal server, web nor in the web console)
- [ ] Can we be more robust against this?
- [ ] Document this part

**Comment by tcompa** [comment]
Thanks for reporting!

This is most likely related to the fact that the cookie domain doesn't match. Then the browser silently rejects the cookie, and all the rest follows (as you observed).

---

Before entering the reproduce-and-transform-into-an-error details:

This one is a well-known gotcha (to us), which did bite me again as recently as #355 (where I at least added a warning in some hidden section of the docs). As of our last discussion (with @zonia3000), our impression was that this is a very low-level configuration error, and it's not surprising that it's a silent failure. I guess we could review this assessment (I'd let Sonia chime in on possible warnings/errors), but I think there are better approaches that require no code change.

1. If one really wants to use `npm run dev` (which is a _development_ command), let's at least avoid suggesting they also include the `open` option. This way it's less likely that they'll end up in `127.0.0.1` instead of `localhost`.
2. In general, it'd be best that a non-developer usage goes through the standard serving command (first build, then use `node` directly, with the appropriate env variables as in https://fractal-analytics-platform.github.io/fractal-web/quickstart/#web-client-startup). When using this, and trying to login from 127.0.0.1:5173, we get a "Cross-site POST form submissions are forbidden" error (note: this is not related to cookie setting, but rather to [this](https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocolheader-and-hostheader)), and then it becomes very clear that something is wrong.

Here is what I would propose:

1. Let's remove `open` from the docs, and let's not recommend people including it (given it has a unexpected behavior in at least one case).
2. Let's clarify in the docs that `npm run dev` is for development, while the build+node command is the recommended command for any other use. This means that we should also include a proper `.env` file in the repository root folder.
3. Let's also move the warning about cookie-domain-matching to the quickstart section, e.g. in the [Web client startup](https://fractal-analytics-platform.github.io/fractal-web/quickstart/#web-client-startup) section.

**Comment by jluethi** [comment]
Sounds good! :) If we refactor the web client startup instructions to focus more on the build & run, this may not appear anyway :)

**Comment by zonia3000** [comment]
In #376 (9f84e726c29c22d940cb6d5d978bd3aacd67c84a) I made the `AUTH_COOKIE_DOMAIN` optional.

If the variable is empty the application will infer the domain from the HTTP request, so the same instance can work both when called from 127.0.0.1 and localhost, without needing to restart.

Notice that you still have to define the variable, but you can keep it empty:

```
AUTH_COOKIE_DOMAIN=
```

I'm not sure in which cases this variable is needed but let's keep it for production environments. Accepting any hostname might have a possible impact on security.

**Comment by zonia3000** [comment]
Additional note on OAuth2 scenario with the URL mismatch.

Suppose that app is configured using

```
OAUTH_GITHUB_REDIRECT_URL=http://localhost:5173/auth/login/oauth2
```

If the user access fractal-web using 127.0.0.1:5173 the login still works, because the callback redirects the user back to localhost:5173. The user doesn't notice anything, except for the URL in the browser that is changed.

If the user changes the port and runs fractal-web using 127.0.0.1:3000 the login stops working, because the callback still redirects to localhost:5173, which doesn't expose a server on that port.
