### ISSUE TITLE
Evaluate use of external JSON-schema-form generator

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#412]
See https://github.com/webgme/svelte-jsonschema-form, which didn't exist when we started this part of fractal-web.

Of course there are pros and cons in taking up one more dependency, but the next time that we'll need to review/update our custom form generator (my guess: as soon as we switch to pydantic v2 in fractal-tasks-core) we should also compare the required effort to the option of using an independent library.

The other one we could look at is https://github.com/restspace/svelte-schema-form.

**Comment by tcompa** [comment]
Great, I'm testing it now!

(the actual issue is #413)

**Comment by zonia3000** [comment]
A report about some experiments with external libraries.

# WebGME Svelte JSON Schema Form

https://github.com/webgme/svelte-jsonschema-form

* It's not clear how to import the CSS, I've only made a test without CSS.
* It has a lot of dependencies: 17 packages as direct dependency.
* It is not clear which draft version of JSON Schema is supported.

* Produces some warnings on console:

```
<ObjectProps> was created with unknown prop 'type' client.js:2098:15
<ObjectProps> was created with unknown prop 'additionalProperties' client.js:2098:15
<ObjectProps> was created with unknown prop 'force'
```

* Using their [playground](https://webgme.github.io/svelte-jsonschema-form/) it looks that it has some problems in handling long descriptions, since it puts them inside the section headers. We can probably make the text multiline by adding some CSS but to move it outside from the header we have to modify the library.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/384dc8c5-ca15-49ca-8014-328a0ff55993)

# Restspace Svelte Schema Form

https://github.com/restspace/svelte-schema-form

* Importing the CSS produces a missing file error, even if the file is there. The README states that "you'll likely need to configure your bundler to interpret importing css to make this work", but there are no examples on how to do that. Tried some different Vite settings and to import .css instead of .scss but it didn't work. Needs more investigation.  I've only made a test without CSS.

```
Error: [postcss] Missing "./dist/css/layout.scss" specifier in "@restspace/svelte-schema-form" package
```

* It doesn't support the case with `anyOf` and `{"type": "null"}` produced by Pydantic-v2 generated JSON Schemas.
* It is not clear which draft version of JSON Schema is supported.
* Produces several accessibility warnings during the build:
```
9:53:28 AM [vite-plugin-svelte] /home/xonya/code/fractal-web/node_modules/@restspace/svelte-schema-form/dist/editors/ListDetail.svelte:131:2
A11y: visible, non-interactive elements with an on:click event must be accompanied by an on:keydown, on:keyup, or on:keypress event.
```

# JSON Editor

https://github.com/json-editor/json-editor

* This library is generic and doesn't depend on a specific framework (Svelte, React, Vue...)
* They say to support Version 3 and Version 4 of the JSON Schema draft. Not clear if this is true or if the information on the README is outdated (for example they have only Bootstrap4 in the list of supported themes, but in another section is clear that they also support a Bootstrap5 theme).

* It seems to be feasible integrating the library in our app, but we have to consider it has a quite different UI, that can be customized only modifying the library, in particular:

  * Missing required properties are highlighted in a separated alert box (validation is done at the form initialization, so the red boxes are immediately visible, even before editing).
  * Descriptions are always visible.
  * To add a new property one has to click on the "Object properties" button, that opens a menu containing all the existing properties and a text input to add more properties.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/2b687a27-69df-4c6c-ad09-15b6ed3a4da2)

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/f087723e-0644-4ba7-952c-44c4bd6c07f4)

I'll open a separate branch to experiment with this library, which seems the one more promising.

**Comment by tcompa** [comment]
Thanks!
For the moment, this exhausts the broad-scope evaluation of 3rd-party libraries. Let's briefly explore `json-editor` in another branch/issue, and only come back here if we learn about other libraries (or we have compelling reasons to adopt one).

**Comment by jluethi** [comment]
Thanks a lot for this investigation & the screenshots @zonia3000 ! It shows how much we're already covering with our current implementation I'd guess.

There are some interesting layout thoughts in how `WebGME` displays the schemas. But it's clearly not an overall library we want to move to at such a stage.

**Comment by zonia3000** [comment]
It is possible to experiment with json-editor using the Sanbox page in branch [external-json-schema-lib](https://github.com/fractal-analytics-platform/fractal-web/tree/external-json-schema-lib).

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/49f9ac74-67cb-4099-a45e-a2d29666da49)
