### ISSUE TITLE
Can we make the workflow page default to an appropriate dataset?

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#445]
Defaulting the workflow page to not showing a dataset is not that intuitive. Can we handle the default smartly, e.g. the last selected dataset is shown as default again?
We don't have that information server-side, but maybe we can cache it client-side?

Alternatively, do we have a "last edited" timestamp for dataset? That would probably be the dataset a user often wants to work with. If that's not available, most recently created may be good.

Best case: Default to last selected, if nothing has been selected in a given session yet, default to the last edited/last created dataset

**Comment by tcompa** [comment]
Here's what we propose with @zonia3000 

# Backend-side

We add some logic in the GET-workflow endpoint, that adds an additional `default_dataset_id` property to the response body.
The logic is the following:
1. Given a workflow, find the latest job associated to it, and set `default_dataset_id` to be the ID of job dataset.
2. If the workflow has no jobs associated with it, find the project dataset with the most recent `timestamp_created`
3. If the project has no dataset, set `default_dataset_id=null`

# Frontend-side

1. If `default_dataset_id` is set, pre-select it in the dropdown menu, while still letting the user modify this selection.
2. If `default_dataset_id` is not set (because the project has no datasets), only expose the current dropdown menu with no option, and display a message like "This project has no datasets" (TBD)

---

cc @jluethi would this work?

**Comment by jluethi** [comment]
I liked the overall scheme. I see 1 edge-case and one wish for addition:

Edge-case:
> Given a workflow, find the latest job associated to it, and set default_dataset_id to be the ID of job dataset.

When does that happen? When the workflow is created? (no job has run yet) 
What if the workflow is created first and then a dataset is created?



For the addition, I'm thinking about in addition is the following user story:
I have an dataset 1. I run a workflow on it.
I then create a dataset 2, go to the workflow page and it defaults to dataset 1 & switch the view to the second dataset. [moment 1]
I start editing the workflow, but leave the page for some reason. I return and the page defaults to dataset 1 again, even though I switched to dataset 2 before [moment 2].

[moment 1] is what I would expect & the correct default
[moment 2] is potentially confusing

Could selecting a dataset on the front-end overwrite the default_dataset_id? e.g. whenever a user selects a different dataset in the dropdown, it then defaults to that one afterwards?


------

I like the idea of having a `default_dataset_id`. Can it be updated by user selection? In that case, the heuristics for how it is initially set isn't that crucial anymore (but the one above makes sense to me!)

**Comment by jluethi** [comment]
Preferred order:

0. What have I selected as a user on the workflow page before. Can be non-persistent, e.g. front-end only
1. If no selection had been made before: Given a workflow, find the latest job associated to it, and set default_dataset_id to be the ID of job dataset (by submission time)
2. If the workflow has no jobs associated with it, find the project dataset with the most recent timestamp_created
3. If the project has no dataset, set default_dataset_id=null

=> 1-3 are backend-side, 0 is front-end side

**Comment by tcompa** [comment]
After reviewing this with @zonia3000  and @ychiucco, we'll start with frontend-only implementation.

For point 2: we use `GET /api/v2/project/1/workflow/1/job/ ` and sort by `start_timestamp`. Then use `dataset_id` for the latest one.

For point 2: we use `GET /api/v2/project/1/dataset/?history=false` and sort by `timestamp_created`. Then use `id`.
