### ISSUE TITLE
Document which env variables are static/dynamic

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#495]
When running with `node` (after a build), the dynamic variables should be provided as part of the environment - let's make sure we know which ones they are.

**Comment by zonia3000** [comment]
I've reviewed all the environment variables that we are using and I propose to load all the variables dynamically. This means that no variable will be set during build time, but they are all read from the shell environment when the service is started. In development mode they are still loaded from the `.env` files.

I think that for sure we want to have some dynamic variables, for example the ones related to logging. It would be very weird having to rebuild the app in order to change the log level. Some other variables rarely change and we might want to set them at build time, but I think that having a mixed approach is more error prone. In general I would use static variables only for values that depends on the build itself, like, for example, the version number (we don't need this, since we are loading it from package.json - it's just an example).

In this way we might also consider to not have to run the build at all in the production machine. We could add in the GitHub release a package containing the files built by the CI and then to update to a new version one can simply download a zip file, unpack it and restart the service, relying on the dynamic environment variables for the configuration. If you think at other systems, containers usually work in that way: you pull the image and then you customize everything with environment variables, without having to rebuild. I'm not proposing to do this right now, if the current upgrade process is simple and valid for our current use cases, but it might be something useful in the future.

Notice that this would revert #390, where we decided to import `PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL` statically because at that time the expectation was to load it from the `.env` file, that wasn't happening in production since I've initially thought at it as a dynamic variable.

Node 20 also has a [built in support to load environment variables from file](https://nodejs.org/en/blog/release/v20.6.0), so in Node 20 we can do the following:

```
node --env-file=.env build
```

These are the variables that we are currently loading statically:

```
FRACTAL_SERVER_HOST
PUBLIC_OAUTH_CLIENT_NAME
PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL
AUTH_COOKIE_NAME
AUTH_COOKIE_DOMAIN
AUTH_COOKIE_PATH
AUTH_COOKIE_SAME_SITE
AUTH_COOKIE_SECURE
AUTH_COOKIE_HTTP_ONLY
```

We can set some good defaults for most of them. For example `AUTH_COOKIE_NAME` doesn't need to be mandatory if we set `fastapiusersauth` as default in the code.

The ones that need to be customized in production are `FRACTAL_SERVER_HOST`, `PUBLIC_OAUTH_CLIENT_NAME`, `PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL` and `AUTH_COOKIE_DOMAIN`. For everything else it is possible to rely on default values.

**Comment by tcompa** [comment]
I agree with this approach, also in view of simplifying the deployment strategy in the future (ref #498 and #496).

> We can set some good defaults for most of them.

This would be quite useful. If the only ones that are strictly required are

> The ones that need to be customized in production are FRACTAL_SERVER_HOST, PUBLIC_OAUTH_CLIENT_NAME, PUBLIC_FRACTAL_ADMIN_SUPPORT_EMAIL and AUTH_COOKIE_DOMAIN.

then I think we are not introducing much friction.

**Comment by zonia3000** [comment]
Done in 3e2bef5d201ce3dfb999a7e40258066dc4f8483c.

I've also removed the `AUTH_COOKIE_MAX_AGE` since it wasn't used. The cookie expiration date is set parsing the expiration time of the `access_token` received from fractal-server.

**Comment by tcompa** [comment]
> Done in [3e2bef5](https://github.com/fractal-analytics-platform/fractal-web/commit/3e2bef5d201ce3dfb999a7e40258066dc4f8483c).

Great. Could we add a list of configuration variables somewhere in the docs? For each variable it would be useful to have a description and its default (if any).

**Comment by zonia3000** [comment]
> Great. Could we add a list of configuration variables somewhere in the docs? For each variable it would be useful to have a description and its default (if any).

Done in 0aa9ab48a4d48ad7c3a424920a378eacb4dd0764.

I've also removed the `AUTH_COOKIE_HTTP_ONLY` variable since there is no reason to configure it, even in development, and, on the other hand, if accidentally set to false it can lead to security issues. It will be always `true`.
