### ISSUE TITLE
Find out what is the client-side (Svelte/fetch) timeout 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#497]
This is only for the record, in connection with recent work on backend timeout errors.

**Comment by zonia3000** [comment]
I did the following test.

I modified the projects endpoint adding a long sleep:

```python
time.sleep(1000)
```

Then I opened the projects page on fractal-web. The timeout happened after 5 minutes:

![Screenshot from 2024-08-07 19-03-27](https://github.com/user-attachments/assets/1a63822a-0610-4203-92c0-f8215514e4ba)


On the frontend the loading animation stops and a 500 Internal Error is displayed.

On the Svelte backend logs I have the following message:

```
TypeError: fetch failed
    at node:internal/deps/undici/undici:12345:11 {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (/home/xonya/code/fractal-web/node_modules/undici/lib/client.js:1048:28)
      at Timeout.onTimeout [as _onTimeout] (/home/xonya/code/fractal-web/node_modules/undici/lib/timers.js:20:13)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```

This shows that the timeout is handled by [undici](https://github.com/nodejs/undici), that is the library that Svelte internally uses to make HTTP calls. Default undici timeout is 5 minutes.

I was able to modify the timeout adding the following to `hooks.server.js`:

```javascript
import { setGlobalDispatcher, Agent } from 'undici';

setGlobalDispatcher(new Agent({
  headersTimeout: 3000
}));
```

In that case the timeout happened after 3 seconds:

![Screenshot from 2024-08-07 19-23-41](https://github.com/user-attachments/assets/29202f07-d03a-4c7e-8a05-4c75d3fcb3db)

I don't think we should modify this value without a good reason, because Svelte may choose to use a different library in the future and it looks that they are not providing options to configure timeouts on Svelte itself.

**Comment by tcompa** [comment]
Great, thanks for reviewing this.

---


> I don't think we should modify this value without a good reason, because Svelte may choose to use a different library in the future and it looks that they are not providing options to configure timeouts on Svelte itself.

Agreed, closing.
