### ISSUE TITLE
Publish build artifacts on github 

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#498]
Let's add a step to GitHub actions that also publishes the build artifacts (one per node version) somewhere on GitHub (likely as a file attached to the release?). And then let's test running fractal-web by fetching the build artifact directly.
Notice that this requires https://github.com/fractal-analytics-platform/fractal-web/issues/495#issuecomment-2128975606. At that point, the update of fractal-web to a new version in production would become even simpler, on the line of
```bash
wget -qO- https://....github.com/..../node-18-fractal-web-1.2.3 | tar xvz -C ./build
VAR1=VALUE1 VAR2=VALUE2 VAR3=VALUE3 node ./build
```
Note that one could also wrap variable exports in a `run_fractal_web.sh` script, or even better:
1. Use node 20, with its `--env-file` option (https://github.com/fractal-analytics-platform/fractal-web/issues/495#issuecomment-2128975606)
2. Run fractal-web as a service (#496), and point the `EnvironmentFile` to the `.env` file.

**Comment by zonia3000** [comment]
I'm publishing the artifacts generated by the `npm pack` command. Notice that by default this command creates a tgz file containing only the sources. I've added the following fields to the package.json file in order to pack the result of the build with its dependencies:

```
  "files": ["build"],
  "bundledDependencies": true
```

The file produced by `npm pack` includes the build folder and other project files (like README and package.json) inside a parent folder named `package`, so during the extraction I suggest to add the `--strip-components=1` to the `tar` command, in order to remove the parent directory.

The name of the tgz file is not customizable since it is derived from the fields `name` and `version` present in the package.json file.

**Comment by tcompa** [comment]
> In CI I'll create the file with npm pack and then rearrange its content using tar (extracting and repacking).

Great, that seems a good solution.

**Comment by zonia3000** [comment]
Done in #492
