### ISSUE TITLE
Parse whole task-package manifest, and show argument forms for tasks

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#513]
This is a placeholder issue, which will become relevant during/after #512.

Briefly: we could let the user upload a whole manifest (anything upload the file, paste the JSON text, point to an URL), parse it to extract the N tasks and their parallel/non-parallel schemas, and show e.g. a dropdown menu with all tasks. By selecting one, the user would see the corresponding form and values.

High-level: this would be quite useful for a user who built their package and wants to review the whole manifest (are tasks all there? do they look OK in the form? and so on..). The parsing of the manifest is quite simple, and based on this JSON Schema https://github.com/fractal-analytics-platform/fractal-server/blob/main/fractal_server/json_schemas/manifest_v2.json

**Comment by tcompa** [comment]
1. User uploads manifest from disk
2. TBD: we may add a validation step, where we validate the manifest against [its schema](https://raw.githubusercontent.com/fractal-analytics-platform/fractal-server/main/fractal_server/json_schemas/manifest_v2.json).
3. Verify that `manifest_version="2"`, `has_args_schemas=true`, and `args_schema_version="pydantic_v1"`.
4. Construct list of task names, and expose it as a dropdown menu
5. When the user picks task A, render the same page as for the single-schema sandbox, with the minor difference that we need to expose both non-parallel and parallel entries (if present). The dropdown menu remains visible on this page.

**Comment by tcompa** [comment]
Example manifest for testing: https://raw.githubusercontent.com/fractal-analytics-platform/fractal-tasks-core/main/fractal_tasks_core/__FRACTAL_MANIFEST__.json

**Comment by zonia3000** [comment]
Screenshot of the new page:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/be927ebe-4265-4653-8bb8-a4f190d7d82e)

Notice that I added to the repo a copy of the manifest JSON Schema (https://github.com/fractal-analytics-platform/fractal-server/blob/main/fractal_server/json_schemas/manifest_v2.json), since it is not possible to automatically include it in the page from GitHub. Using the `<script>` tag it is possible to load JavaScript files as remote resources, but not JSON files. I've tried also with a possible workaround using an `<iframe>`, but that is disallowed by a security header added by GitHub server (`X-Frame-Options: DENY`), so the only option is to have a local copy of it.

**Comment by tcompa** [comment]
First quick comment (cc @jluethi): should we stick with just supporting V2 manifests, rather than legacy/v2?

**Comment by jluethi** [comment]
That's awesome!

Let's stick with only v2 manifest for sure! We can just show an error if the manifest has an older version than V2 :)

This new manifest version is super powerful during local task development, as the whole manifest gets created by the dev tooling and can then just be uploaded. Can one drag & drop the manifest in there? [if that's tricky to implement, not critical]

**Comment by zonia3000** [comment]
I've added a drag and drop area for the manifest file:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/663a61a9-9943-4b03-a28b-b6d8e35cab45)

**Comment by jluethi** [comment]
That's awesome! Will make for a neat demo! :) 👏🏻
