### ISSUE TITLE
Invalid value in form field is silently discarded upon save

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#519]
When an optional field is set to something invalid (e.g. characters instead of digits), we show a small error message as expected:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/3862206/fdb8f389-4ef1-4282-9225-a72d7fd8240e)

However one can still click "save changes", and the validation and backend calls will take place with the corresponding field unset.

Is this the expected behavior, or should we raise an error when clicking "save changes" if there are some invalid fields?

**Comment by jluethi** [comment]
From a user-experience perspective, discarding the wrong value during saving seems suboptimal. Already good that we show the warning, but we then either:
a) should not allow to save while there is such a warning
or 
b) fail upon validation

Whether it's easier to add a state to the save button (can you currently save or is a warning remaining) or do this upon validation, I don't have a strong opinion on at this stage :)

**Comment by zonia3000** [comment]
A comment on this, since it is a tricky one.

One could imagine to set the "something invalid" text to the object field and let ajv validate it. This is not possible and depends on how browsers work, so this situation has to be treated as a special case. Indeed there is no way to retrieve the "something invalid" text from an input having `type="number"`: if it contains invalid text the result will always be an empty string.

I quote from the [HTML standard](https://html.spec.whatwg.org/multipage/input.html#number-state-%28type=number%29):

>  User agents must not allow the user to set the value to a non-empty string that is not a valid floating-point number. [...] User agents should allow the user to set the value to the empty string.

There is also a big difference in how Firefox and Chrome handles this. In Firefox the user can insert any character in the field, while Chrome blocks any textual character, except a single `e` (for writing numbers using the scientific notation), so in Chrome is much more difficult to trigger the invalid state.

The only thing that we can check is the [badInput property](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/badInput) on the field. I'm storing it and checking it during the validation (I put this check after the ajv validation). The result is a more generic error message:

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/b0653c2e-f107-484b-9b80-2871208849d0)

Notice that the text of the field is still in grey color, since the field internally is still empty.

**Comment by jluethi** [comment]
> There is also a big difference in how Firefox and Chrome handles this. In Firefox the user can insert any character in the field, while Chrome blocks any textual character, except a single e (for writing numbers using the scientific notation), so in Chrome is much more difficult to trigger the invalid state.

Interesting.

Re badInput error:
If we do this, that seems reasonable to me. Let's not go further in catching this then. The only thing we can improve is the error message content & formatting (if possible). We don't really need the "There has been an error, reason" section, just the reason (i.e. just the message). And is it possible to mention which field the error comes from, e.g. foo contains an invalid input type? If not, it's marked in the form, so also fine.

> Notice that the text of the field is still in grey color, since the field internally is still empty.

That's fine by me

**Comment by zonia3000** [comment]
I thought about a different approach. 
When a badInput state is detected the returned form data has the bad input values replaced with an "invalid" placeholder text (independent on what the user typed) to trigger the ajv validation. Internally the field is still empty.

![image](https://github.com/fractal-analytics-platform/fractal-web/assets/5459334/0b13baf6-7610-4258-a3cf-d9aa04671366)

Regarding the "There has been an error, reason", that is a generic issue and we have opened #483 to keep track of it.

**Comment by jluethi** [comment]
That's fine by me :)
