### ISSUE TITLE
Expose link to viewer next to each image in dataset image-list page

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#527]
This is an experimental feature, not to be merged.

The button would link to our own vizarr/data service (e.g. on port 3000), and use the image URL (aka absolute path).
Notice that we would need to map cluster paths into VM paths, but at the testing level we can work around this need in a few ways (e.g. by mounting the cluster share on the VM with the same absolute path, or using symlinks, ...).

**Comment by zonia3000** [comment]
In the `link-to-viewer` branch I added the new experimental link. The branch has been created from `summer_improvements`, so it contains also those commits.

The dataset page has a new "View" button that opens a link (in a new tab) to the vizarr viewer:

![Screenshot from 2024-08-07 18-26-05](https://github.com/user-attachments/assets/bd14dea4-ab92-4a00-835f-2d7ccf62242f)

The viewer link can be configured using the `PUBLIC_FRACTAL_VIZARR_VIEWER_URL` environment variable. If the variable is not present the link is not displayed.

**Comment by jluethi** [comment]
Neat! That will be great to add to the Science Cluster deployment!

How does the `PUBLIC_FRACTAL_VIZARR_VIEWER_URL` need to be set? How does it handle the fact that the base of the path is different on the VM that streams the data from the cluster?

**Comment by zonia3000** [comment]
> How does the `PUBLIC_FRACTAL_VIZARR_VIEWER_URL` need to be set?

It's like all the other variables that we are setting in the env file or via `export` when starting from the script.
It's read at runtime, when the fractal-web app start.

For local testing we can use:

```
PUBLIC_FRACTAL_VIZARR_VIEWER_URL=http://localhost:3000/vizarr
```

> How does it handle the fact that the base of the path is different on the VM that streams the data from the cluster?

I'm not sure if I have understood the question correctly.

If you are talking about the paths of the files on disk I suppose that, as suggested by @tcompa in the first comment of this issue, we can "mount the cluster share on the VM with the same absolute path". That has to be tested.

Notice that, from an external point of view, the URL of fractal-web must have the same main domain of the URL of vizarr-viewer, otherwise cookies authentication will not work (more details on [fractal-vizarr-viewer readme](https://github.com/fractal-analytics-platform/fractal-vizarr-viewer?tab=readme-ov-file#note-about-the-domain-constraint)), so we added some proxy configuration (that is already in place).

**Comment by jluethi** [comment]
> If you are talking about the paths of the files on disk I suppose that, as suggested by @tcompa in the first comment of this issue, we can "mount the cluster share on the VM with the same absolute path". That has to be tested.

Ah, makes sense. We haven't set that up yet, but going that route makes sense.
