### ISSUE TITLE
Nested default parameters not shown in workflow page

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#537]
For different task with Pydantic models (e.g. the Cellpose task with the Advanced Cellpose Model Params or the Normalize model within the channel) don't show the defaults of those models correctly in the workflow page, while it's displayed correctly in the sandbox page.

Workflow page with Fractal web 1.3.2
<img width="1357" alt="Screenshot 2024-07-24 at 17 46 34" src="https://github.com/user-attachments/assets/57ed44fa-3e80-4e22-840d-9c4dcb59616a">

Workflow page with Fractal web 1.3.0
<img width="1357" alt="Screenshot 2024-07-24 at 17 46 29" src="https://github.com/user-attachments/assets/3a5299fd-46ea-470e-9309-a36346507e52">

Sandbox page
<img width="1357" alt="Screenshot 2024-07-24 at 17 46 43" src="https://github.com/user-attachments/assets/27cb5d37-c020-423c-a0b6-4ec21573fdfa">

I think the issue is with models that are specified as a reference:
```
"advanced_cellpose_model_params": {
            "$ref": "#/definitions/CellposeModelParams",
            "title": "Advanced_Cellpose_Model_Params",
            "description": "Advanced Cellpose model parameters that are passed to the Cellpose `model.eval` method."
          },
```

Originally reported by @adrtsc

**Comment by jluethi** [comment]
Schema that reproduces the issue:
[__FRACTAL_MANIFEST__.json](https://github.com/user-attachments/files/16364727/__FRACTAL_MANIFEST__.json)

Both for the Advanced Cellpose Model Params & the Normalize model within the channel in the Cellpose Segmentation task

**Comment by tcompa** [comment]
Quick feedback: are we looking at the same observations as in the https://github.com/fractal-analytics-platform/fractal-tasks-core/pull/738 discussion?

I'll need to double check, but our first understanding is that the backend does not populate default values for non-top-level arguments. This means we would need to modify the task call signature (similar to what we did in the PR mentioned above) so that the default is with the top-level arguments and not only in the nested ones.

More on this later.

**Comment by tcompa** [comment]
In https://github.com/fractal-analytics-platform/fractal-web/issues/538, I laid out our current review of this issue, and the different behavior between sandbox and fractal-web is understood. 

I'd say that the current issue is not a regression with recent fractal-web versions, but it's rather due to recent changes in the task call signatures which we did not review carefully enough (interesting side question: how should we test that a new schema produces the expected UI? TBD).

I think a change to fractal-web will be necessary (ref https://github.com/fractal-analytics-platform/fractal-web/issues/539), but it's not something that can be rushed through. My suggestion for a quick fix is to review the task call-signature and look for a workaround that works as expected. I will start looking at some options over there.

**Comment by jluethi** [comment]
> interesting side question: how should we test that a new schema produces the expected UI

I'd say the sandbox is how task developers will test whether a given manifest will have the desired UI behavior. And eventually having it on the actual instance. But this highlights the importance of having the sandbox fully reflect how the front-end will work with its backend interaction more. That may mean simplifying the backend (as in https://github.com/fractal-analytics-platform/fractal-server/issues/1686) or adding some complexity to the sandbox where well-understood and reasonable.

The design goal to work towards here being that task developers can fully verify the eventual behavior by using the sandbox. The fact that there is complexity in the Pydantic + json manifests + backend server with defaults should not be a surprise in retrospective :) Let's use this to reflect on which complexity in these systems is actually warranted (=> will be also added to the sandbox) and which complexity can be refactored away.

**Comment by tcompa** [comment]
> That may mean simplifying the backend (as in https://github.com/fractal-analytics-platform/fractal-server/issues/1686) or adding some complexity to the sandbox where well-understood and reasonable.

This was implemented in the former way, by simplifying the backend.
Refs:
* https://github.com/fractal-analytics-platform/fractal-server/pull/1688
* https://github.com/fractal-analytics-platform/fractal-web/issues/537

When using fractal-server 2.3.6, upon adding a cellpose task we observe the expected behavior:
![image](https://github.com/user-attachments/assets/7c27086b-f902-49f2-b7f6-29d407c924e9)
![image](https://github.com/user-attachments/assets/61c5e711-f357-4329-94a3-5e6c6f073430)

**Comment by tcompa** [comment]
Thanks a lot @adrtsc for reporting this! It led to very useful discussions and updates.
