### ISSUE TITLE
New feature: admin page for running job-submission healthcheck

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#541]
[this is clearly non urgent]

Main goal: after a version update, the admin can quickly make a basic verification that job submission (and therefore SLURM integration) works fine.

---

This new page would have a simple input interface, which asks the admin to provide a zarr directory (or other arguments which are not coming to mind at the moment).
Upon receiving this input, the page would then go through a sequence of steps:

1. Create a project (name could be anything, e.g. "test_{usernam}_{random_integer}")
2. Create a dataset, with the admin-provided zarr directory
3. Create a workflow
4. If not existing, create a non-parallel task with a given source (e.g. "job_submission_health_check"), with `command_non_parallel="echo"`.
5. Submit the workflow
6. If all up to here was successful, redirect to the workflow page. If anything failed, stop the procedure and display an error.

Note: we could also encode this in a backend endpoint, but it's actually easier to do it here because we "just" need to make API calls (rather than writing new custom Python code) and we get the most realistic emulation of a user's steps.

---

Note: the cleanup does not need to be automated: after the admin is done, they can go and delete the project and be done.

**Comment by zonia3000** [comment]
This is the simple form:

![image](https://github.com/user-attachments/assets/8725de18-5a2e-4a9f-b27a-6238fe5618f1)

A small spinner is displayed in the button while the test is running. In case of success we are redirected to the workflow page.

I've forced triggering an error during the process and we can see a message describing the failed step together with the error message:

![image](https://github.com/user-attachments/assets/f0350fbf-0010-48c7-b1e3-9e4bd9f87619)

Extra note. I've refactored the buttons in the main admin area page, since we are now having some of them.

![image](https://github.com/user-attachments/assets/ea8914c9-1ca2-4635-946a-9a856ddaa036)
