### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#622]

**Comment by jluethi** [comment]
Here are some of the logo assets. Ping me if you need something specific at a given resolution :)

I'm open to different ideas of using the Fractal logo. E.g. using it instead of "Home", or showing it on the Home landing page.

![Fractal_favicon](https://github.com/user-attachments/assets/513687c1-55a4-4be7-ae8b-435f44b3b1e6)
![Fractal_logo_F_only_high_res](https://github.com/user-attachments/assets/82ce1deb-dd57-49f7-849b-539aec05aa21)
![Fractal_logo_F_only](https://github.com/user-attachments/assets/a5f00230-b79b-48d0-a1d7-c09771440e86)
![Fractal_F_V3_I2K_transparent](https://github.com/user-attachments/assets/44b7eb8e-8adb-4381-95bb-53dc6993d4db)

**Comment by zonia3000** [comment]
I added it both to the home page and instead of "Home". It also appears in the browser tab as favicon.

![image](https://github.com/user-attachments/assets/59df05d5-d581-4ee6-a93c-7c515da1de8c)

**Comment by jluethi** [comment]
That's awesome! :)
