### ISSUE TITLE
The user shall be able to export a Workflow

### ISSUE THREAD

**Issue by rkpasia** [fractal-analytics-platform/fractal-web#66]
The user shall be able to trigger the export of a workflow to a local file that they specify.

Note that this requires ability to write a file, similar to the possibility of reading a file in #42.

**Comment by tcompa** [comment]
Minor comment: can we  we modify stringify so that the exported workflow looks like:
```JSON
{
    "something": "else",
    "asd": "asd",
}
```
rather than
```JSON
{"something": "else", "asd": "asd",}
```
?

It makes the exported file much more readable.

I think that setting [space=2](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#parameters) should work.

**Comment by rkpasia** [comment]
> can we we modify stringify so that the exported workflow [...] makes file much more readable

Fixed by by https://github.com/fractal-analytics-platform/fractal-web/commit/3b7c45f7a1048100732253f35045fc618dcff1b2
