### ISSUE TITLE
In "Tasks" page, add "Version" column to the "Task collections" table

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#72]
Let's have these columns:
* Timestamp
* Package
* Version  (currently missing column)
* Status
* Options (currently missing column title)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)

**Comment by rkpasia** [comment]
If a user specifies a version number, that is shown in the `Version` column. Otherwise, _unspecified_ is used as placeholder.

The server does not provide any info about `version`, or the package version from which the tasks are imported. At least not in the tests I made.

![Screenshot 2023-03-27 alle 14 53 59](https://user-images.githubusercontent.com/5786033/227945555-0dbea429-acd8-488f-8f4f-ee46c1f1b069.png)
