### ISSUE TITLE
Login fails silently on Safari

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#73]
Using the current main of fractal-web, I can launch a web server and, when using Chrome, log in + do other things like task collection & project creation.

If I try the same thing on the same running web server using Safari (sometimes it defaults to opening it in safari), I get the overview page, I can click Login + enter credentials. But that then just puts me back on the overview page. I'm still not logged in (can't see Projects or Tasks subpages) and see no error message.

Is there a conscious decision to be Chrome only for the moment?

**Comment by rkpasia** [comment]
This unfortunately is due to security/privacy policies of safari.

Basically, the client is served by a nodejs server located at (example) `localhost:5432`.
The fractal server, on the other hand, is located at (example) `localhost:8000`.

Due to this host difference, the browser prevent to accept cookies that are not coming directly from `localhost:5432` thus rejecting to save the authentication session coming from `localhost:8000`.

This issue could be solved in production having both servers to be hosted on a common root domain `*.eample.com`.

There could be workarounds, but haven't had the time to investigate them further.

**Comment by jluethi** [comment]
Ah, thanks for the explanation! :)

In that case, let's keep testing to Chrome for the time being and see whether we this workaround will work once we use actual domains later.
